"""Initial migration - create user authentication and data persistence tables

Revision ID: 398a6ce9cf4a
Revises:
Create Date: 2025-07-27 01:22:18.899468

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "398a6ce9cf4a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_entries",
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("cache_key", sa.String(length=255), nullable=False),
        sa.Column("namespace", sa.String(length=100), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=True),
        sa.Column("data_type", sa.String(length=50), nullable=False),
        sa.Column("ttl", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("last_accessed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cache_entries_cache_key"), "cache_entries", ["cache_key"], unique=False
    )
    op.create_index(
        op.f("ix_cache_entries_created_at"),
        "cache_entries",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cache_entries_expires_at"),
        "cache_entries",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cache_entries_namespace"), "cache_entries", ["namespace"], unique=False
    )
    op.create_index(
        op.f("ix_cache_entries_updated_at"),
        "cache_entries",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_cache_key_namespace",
        "cache_entries",
        ["cache_key", "namespace"],
        unique=True,
    )
    op.create_table(
        "data_retention_policies",
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_table", sa.String(length=100), nullable=False),
        sa.Column("target_column", sa.String(length=100), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_run", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_retention_policies_created_at"),
        "data_retention_policies",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_retention_policies_name"),
        "data_retention_policies",
        ["name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_data_retention_policies_next_run"),
        "data_retention_policies",
        ["next_run"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_retention_policies_target_table"),
        "data_retention_policies",
        ["target_table"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_retention_policies_updated_at"),
        "data_retention_policies",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "analysis_results",
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column(
            "user_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True
        ),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("analysis_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("results", sa.JSON(), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.Column("analysis_metadata", sa.JSON(), nullable=True),
        sa.Column("processing_time", sa.Integer(), nullable=True),
        sa.Column("data_points", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_results_analysis_type"),
        "analysis_results",
        ["analysis_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_created_at"),
        "analysis_results",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_expires_at"),
        "analysis_results",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_file_hash"),
        "analysis_results",
        ["file_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_filename"),
        "analysis_results",
        ["filename"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_status"), "analysis_results", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_results_updated_at"),
        "analysis_results",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_user_id"),
        "analysis_results",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column(
            "user_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True
        ),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_description", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_path", sa.String(length=255), nullable=True),
        sa.Column("event_data", sa.JSON(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_event_type"), "audit_logs", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_severity"), "audit_logs", ["severity"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_updated_at"), "audit_logs", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column(
            "user_id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True
        ),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_created_at"), "sessions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_sessions_ip_address"), "sessions", ["ip_address"], unique=False
    )
    op.create_index(
        op.f("ix_sessions_session_id"), "sessions", ["session_id"], unique=True
    )
    op.create_index(
        op.f("ix_sessions_updated_at"), "sessions", ["updated_at"], unique=False
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_updated_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_session_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_ip_address"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_created_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_updated_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_severity"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_event_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_analysis_results_user_id"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_updated_at"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_status"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_filename"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_file_hash"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_expires_at"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_created_at"), table_name="analysis_results")
    op.drop_index(
        op.f("ix_analysis_results_analysis_type"), table_name="analysis_results"
    )
    op.drop_table("analysis_results")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_data_retention_policies_updated_at"),
        table_name="data_retention_policies",
    )
    op.drop_index(
        op.f("ix_data_retention_policies_target_table"),
        table_name="data_retention_policies",
    )
    op.drop_index(
        op.f("ix_data_retention_policies_next_run"),
        table_name="data_retention_policies",
    )
    op.drop_index(
        op.f("ix_data_retention_policies_name"), table_name="data_retention_policies"
    )
    op.drop_index(
        op.f("ix_data_retention_policies_created_at"),
        table_name="data_retention_policies",
    )
    op.drop_table("data_retention_policies")
    op.drop_index("ix_cache_key_namespace", table_name="cache_entries")
    op.drop_index(op.f("ix_cache_entries_updated_at"), table_name="cache_entries")
    op.drop_index(op.f("ix_cache_entries_namespace"), table_name="cache_entries")
    op.drop_index(op.f("ix_cache_entries_expires_at"), table_name="cache_entries")
    op.drop_index(op.f("ix_cache_entries_created_at"), table_name="cache_entries")
    op.drop_index(op.f("ix_cache_entries_cache_key"), table_name="cache_entries")
    op.drop_table("cache_entries")
    # ### end Alembic commands ###
